# Topic 2 Randomness

In [1]:
# generating numbers
import numpy as np

# flip a fair coin - a single coin toss
np.random.binomial(1, 0.5)

0

In [2]:
# Flip a fair coin 100 times.
np.random.binomial(1, 0.5, 100)

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0])

In [5]:
# Flip a fair coin 100 times.
np.random.binomial(100, 0.5)

54

In [6]:
# Keep flipping coins until we get three examples of getting five heads in ten coin tosses.

# Number of examples.
N = 3

# Keep track of number of arrays generated.
total_no = 0

# Keep trying until we get three examples.
while N > 0:
    # Add 1 to total.
    total_no = total_no + 1
    # Toss 10 coins.
    tosses = np.random.binomial(1, 0.5, 10)
    # Check if we got five heads.
    if tosses.sum() == 5:
        # If we got 5 heads, print the list of heads/tails.
        print(tosses)
        # Reduce the number of examples left to find by 1.
        N = N - 1

print(f'Total generated: {total_no}')

[1 0 1 1 1 0 1 0 0 0]
[1 0 0 0 1 1 1 0 0 1]
[1 0 0 0 1 1 1 0 0 1]
Total generated: 44


#### Key Question: 
How many other ways are there in total to flip ten coins and get five heads?

In [8]:
(10 * 9 * 8 * 7 * 6) // (5 * 4 * 3 * 2 * 1)

252

In [9]:
(10 * 9 * 8 * 7) // (4 * 3 * 2 * 1)

210

In [5]:
# Number of combinations.
no_combs = 0

# Select the first position.
for first in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
    # Select the position for the second position.
    for second in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
        # Make sure the first and second positions are different.
        if not first == second:
            # Print the combination.
            print(f'({first:2},{second:2})')
            # Add one to number of combinations.
            no_combs = no_combs + 1

# Print total number of combinations.
print(f'Total combinations is {no_combs}.')


( 1, 2)
( 1, 3)
( 1, 4)
( 1, 5)
( 1, 6)
( 1, 7)
( 1, 8)
( 1, 9)
( 1,10)
( 2, 1)
( 2, 3)
( 2, 4)
( 2, 5)
( 2, 6)
( 2, 7)
( 2, 8)
( 2, 9)
( 2,10)
( 3, 1)
( 3, 2)
( 3, 4)
( 3, 5)
( 3, 6)
( 3, 7)
( 3, 8)
( 3, 9)
( 3,10)
( 4, 1)
( 4, 2)
( 4, 3)
( 4, 5)
( 4, 6)
( 4, 7)
( 4, 8)
( 4, 9)
( 4,10)
( 5, 1)
( 5, 2)
( 5, 3)
( 5, 4)
( 5, 6)
( 5, 7)
( 5, 8)
( 5, 9)
( 5,10)
( 6, 1)
( 6, 2)
( 6, 3)
( 6, 4)
( 6, 5)
( 6, 7)
( 6, 8)
( 6, 9)
( 6,10)
( 7, 1)
( 7, 2)
( 7, 3)
( 7, 4)
( 7, 5)
( 7, 6)
( 7, 8)
( 7, 9)
( 7,10)
( 8, 1)
( 8, 2)
( 8, 3)
( 8, 4)
( 8, 5)
( 8, 6)
( 8, 7)
( 8, 9)
( 8,10)
( 9, 1)
( 9, 2)
( 9, 3)
( 9, 4)
( 9, 5)
( 9, 6)
( 9, 7)
( 9, 8)
( 9,10)
(10, 1)
(10, 2)
(10, 3)
(10, 4)
(10, 5)
(10, 6)
(10, 7)
(10, 8)
(10, 9)
Total combinations is 90.


### Exercise 1

It is somewhat interesting that (5 * 4 * 3 * 2 * 1) perfectly divides (10 * 9 * 8 * 7 * 6) - there's no remainder.

If we only wanted exactly four heads as opposed to five, the equivalent calculation would be (10 * 9 * 8 * 7) / (4 * 3 * 2 * 1).

(i) Does that evenly divide too? 
That divides evenly
(ii) What is the formula in general?
The formula for repeating, non ordered combinations is 

(r + n − 1)! / r!(n − 1)!

where n is the number of things to choose from,
and we choose r of them
repetition is allowed,
order doesn't matter. 
https://www.mathsisfun.com/combinatorics/combinations-permutations.html 
 
(ii) Does it always come out as a positive whole number?
It will always come out positive because n is a number of things or a count of things which is not negative and likewise counts are whole numbers. 

https://math.stackexchange.com/questions/11601/proof-that-a-combination-is-an-integer
https://www.quora.com/Are-permutations-and-combinations-always-a-whole-number



In [6]:
(10 * 9 * 8 * 7) // (4 * 3 * 2 * 1)

210

#### Exercise 2

(i) Note that there are the same number of ways to get 4 tails as there to get 4 heads. Explain why this is.
The probability is 50/50 for tails or heads so the calculation will resolve to the same result. 

(ii) If you get 4 heads how many tails will you get, name the calculation in Maths and explain. 
If you flip a fair coin ten times and you get 4 heads, you will get 6 tails. It's called subtraction. 